In [1]:
import os, os.path
import numpy as np
import pandas as pd
import data_structures as ds
import model_afolu as ma
import model_circular_economy as mc
import model_ippu as mi
import model_energy as me
from model_circular_economy import CircularEconomy
from model_socioeconomic import Socioeconomic
import setup_analysis as sa
import support_functions as sf
import importlib
import time
import warnings
import matplotlib.pyplot as plt
importlib.reload(ds)
importlib.reload(sa)
importlib.reload(sf)
importlib.reload(ma)
importlib.reload(mc)
importlib.reload(mi)
importlib.reload(me)

/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:630: UserWarning: Invalid subsector attribute 'key_varreqs_partial'. Valid return type values are:'pycategory_primary', 'abv_subsector', 'sector', 'abv_sector', 'key_varreqs_all'
  warnings.warn(f"Invalid subsector attribute '{return_type}'. Valid return type values are:{valid_rts}")
/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:1617: UserWarning: clean_partial_category_dictionary: Invalid categories values 'wood' dropped when cleaning the dictionary. Category values not found.
  warnings.warn(f"clean_partial_category_dictionary: Invalid categories values {missing_vals} dropped when cleaning the dictionary. Category values not found.")
/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:630: UserWarning: Invalid subsector attribute 'key_varreqs_partial'. Valid return type values are:'pycategory_primary', 'abv_subsector', 'sector', 'abv_sector', 'key_varreqs_all'
  warnings.warn(f"Invalid subsector attribute '{return_type}'. Valid return type values are:{valid_rts}")
/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:1617: UserWarning: clean_partial_category_dictionary: Invalid categories values 'wood' dropped when cleaning the dictionary. Category values not found.
  warnings.warn(f"clean_partial_category_dictionary: Invalid categories values {missing_vals} dropped when cleaning the dictionary. Category values not found.")

In [7]:
fp_wkbk = "/Users/jsyme/Documents/Projects/FY21/SWCHE131_1000/Data/Energy/WorldEnergyBalancesHighlights2021.xlsx"
df_read = pd.read_excel(fp_wkbk, sheet_name = "TimeSeries_1971-2020", skiprows = 1)
df_pop = pd.read_csv("/Users/jsyme/Documents/Projects/FY21/SWCHE131_1000/Data/API_SP.POP.TOTL_DS2_en_csv_v2_4150863/API_SP.POP.TOTL_DS2_en_csv_v2_4150863.csv", skiprows = 2)
df_gdp = pd.read_csv("/Users/jsyme/Documents/Projects/FY21/SWCHE131_1000/Data/API_NY.GDP.MKTP.KD_DS2_en_csv_v2_4150850/API_NY.GDP.MKTP.KD_DS2_en_csv_v2_4150850.csv", skiprows = 3)

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2020 Provisional,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1368.25,1648.41,1685.22,1640.36,...,12331.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0,0,0,0,...,19.6295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-541.424,-614.718,-738.939,-745.383,...,-10541.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),884.297,923.25,945.542,928.323,...,1648.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Australia,"Coal, peat and oil shale","Electricity, CHP and heat plants (PJ)",01. Australia,"01. Coal, peat and oil shale","05. Electricity, CHP and heat plants (PJ)",-516.539,-569.922,-577.9,-617.948,...,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6155,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),..,..,..,..,...,2.16196e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6156,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3.90541e+06,4.24182e+06,4.60628e+06,4.55261e+06,...,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6157,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),111087,152475,203196,272711,...,2.67886e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6158,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1.2406e+06,1.30421e+06,1.3216e+06,1.46018e+06,...,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6159,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5.25716e+06,5.69859e+06,6.13114e+06,6.28752e+06,...,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
all_countries = set(df_read["Country"])
yrs = [2017, 2018, 2019]
country = "Mexico"

# TEMPORARY


df_tmp = df_read[df_read["Country"] == country]
df_tmp = df_tmp[["Product", "Flow"] + yrs]
dict_repl = {"Nuclear": "Electricity", "Renewables and waste": "Electricity"}
df_tmp["Product"].replace(dict_repl, inplace = True)

dict_agg = {"Product": "first", "Flow": "first"}
dict_agg.update(dict(zip(yrs, ["sum" for x in yrs])))
df_tmp = df_tmp.groupby(["Product", "Flow"]).agg(dict_agg).reset_index(drop = True)

vec_pop = np.array(df_pop[df_pop["Country Name"] == country][[str(x) for x in yrs]])
vec_gdp = np.array(df_gdp[df_gdp["Country Name"] == country][[str(x) for x in yrs]])/(10**9)
# array
array_div = np.ones((len(keep_flows), len(yrs)))
array_div[0,:] = vec_pop
array_div[1,:] = vec_gdp
df_div = pd.DataFrame(array_div, columns = [str(x) + "_div" for x in yrs])
keep_flows = ["Residential (PJ)", "Commercial and public services (PJ)", "Other final consumption (PJ)"]
df_div["Flow"] = keep_flows
# rename for values
df_tmp = pd.merge(df_tmp, df_div, how = "left")
df_tmp = df_tmp.rename(columns = dict(zip(yrs, [str(x) + "_val" for x in yrs])))

array_vals_norm = np.array(df_tmp[[str(x) + "_val" for x in yrs]])/np.array(df_tmp[[str(x) + "_div" for x in yrs]])
df_vals_norm = pd.DataFrame(array_vals_norm, columns = [str(x) for x in yrs])
df_tmp = pd.concat([df_tmp, df_vals_norm], axis = 1)
df_tmp["mean"] = df_tmp[[str(x) for x in yrs]].apply(np.mean, axis = 1)
df_tmp = df_tmp[df_tmp["Flow"].isin(keep_flows)]


df_tmp_not_total = df_tmp[~df_tmp["Product"].isin(["Total"])].reset_index(drop = True).rename(columns = {"mean": "value"})
df_tmp_total = df_tmp[df_tmp["Product"].isin(["Total"])].reset_index(drop = True).rename(columns = {"mean": "total"})
df_tmp_compare = pd.merge(df_tmp_not_total[["Product", "Flow", "value"]], df_tmp_total[["Flow", "total"]], how = "left")
df_tmp_compare["proportion"] = np.array(df_tmp_compare["value"])/np.array(df_tmp_compare["total"])



pop = int(df_pop[df_pop["Country Name"] == "Costa Rica"]["2019"].iloc[0])#5046057
gdp = float(df_gdp[df_gdp["Country Name"] == "Costa Rica"]["2019"].iloc[0])/(10**9)#63.43013
vec_dat = [pop, gdp, 1]
df_dat = pd.DataFrame({"Flow": keep_flows, "cr": vec_dat})

df_cr = pd.merge(df_tmp_compare, df_dat)
df_cr["est"] = np.array(df_cr["value"])#*np.array(df_cr["cr"])
df_cr["est_total"] = np.array(df_cr["total"])#*np.array(df_cr["cr"])

# assume some proprtion of electric demand that is used for heat energy (cooking, heating the home, etc.)
prop_elec_heat = 0.3

df_cr_new = []

fld_to_use = "mean"
for flow in keep_flows:
    
    df_cr_tmp = df_cr[df_cr["Flow"] == flow]
    elec = float(df_cr_tmp[df_cr_tmp["Product"] == "Electricity"][fld_to_use].iloc[0])#*prop_elec_heat
    elec_heat = elec*prop_elec_heat
    elec_appl = elec - elec_heat
    
    vec_out_nm = ["Electricity - Appliance", "Electricity - Heat"]
    vec_out_dat1 = [elec_appl, elec_heat]
    
    df_filt = df_cr_tmp[df_cr_tmp["Product"] != "Electricity"]
    non_elec = np.array(df_filt[fld_to_use])
    non_elec_nms = df_filt["Product"]
    heat_ener_total = np.sum(non_elec) + elec_heat
    
    vec_out_nm += list(non_elec_nms)
    vec_out_dat1 += list(df_filt[fld_to_use])
    
    vec_out_dat2 = [elec_appl] + [heat_ener_total for x in range(len(df_filt) + 1)]
    
    df_cr_new_app = pd.DataFrame({"Flow": [flow for x in vec_out_dat2], "Product": vec_out_nm, "num": vec_out_dat1, "den": vec_out_dat2})
    df_cr_new.append(df_cr_new_app)
    

df_cr_new = pd.concat(df_cr_new, axis = 0).reset_index(drop = True)
df_cr_new["props"] = np.array(df_cr_new["num"])/np.array(df_cr_new["den"])


df_1 = pd.DataFrame({"Product": ["Oil products"], "pd": [2]})
df_cr_new = pd.merge(df_cr_new, df_1, how = "left")
df_cr_new["pd"].fillna(1, inplace = True)
df_cr_new["props_adj"] = np.round(np.array(df_cr_new["props"])/np.array(df_cr_new["pd"]), 3)

KeyError: 'mean'

In [171]:
#df_cr_new[df_cr_new["Flow"] == "Other final consumption (PJ)"].sort_values(by = ["Flow", "Product"])
df_tmp_compare

,Product,Flow,value,total,proportion
0,"Coal, peat and oil shale",Commercial and public services (PJ),0.000000e+00,0.141295,0.000000
1,"Coal, peat and oil shale",Other final consumption (PJ),2.923690e+00,458.999896,0.006370
2,"Coal, peat and oil shale",Residential (PJ),0.000000e+00,0.000006,0.000000
3,"Crude, NGL and feedstocks",Commercial and public services (PJ),0.000000e+00,0.141295,0.000000
4,"Crude, NGL and feedstocks",Other final consumption (PJ),0.000000e+00,458.999896,0.000000
5,"Crude, NGL and feedstocks",Residential (PJ),0.000000e+00,0.000006,0.000000
6,Electricity,Commercial and public services (PJ),8.168922e-02,0.141295,0.578145
7,Electricity,Other final consumption (PJ),1.284444e+02,458.999896,0.279835
8,Electricity,Residential (PJ),3.807550e-06,0.000006,0.645387
9,Heat,Commercial and public services (PJ),0.000000e+00,0.141295,0.000000
10,Heat,Other final consumption (PJ),0.000000e+00,458.999896,0.000000
11,Heat,Residential (PJ),0.000000e+00,0.000006,0.000000
12,Natural gas,Commercial and public services (PJ),8.494765e-03,0.141295,0.060121
13,Natural gas,Other final consumption (PJ),1.379790e+01,458.999896,0.030061
14,Natural gas,Residential (PJ),2.213972e-07,0.000006,0.037527
15,Oil products,Commercial and public services (PJ),5.111130e-02,0.141295,0.361734
16,Oil products,Other final consumption (PJ),3.138339e+02,458.999896,0.683734
17,Oil products,Residential (PJ),1.870692e-06,0.000006,0.317086

In [167]:
df_tmp[(df_tmp["Flow"] == "Residential (PJ)") & (df_tmp["Product"] != "Total")]["2017_val"].sum()
#df_tmp[(df_tmp["Flow"] == "Residential (PJ)") & (df_tmp["Product"] == "Total")]["2017_val"]
df_tmp

,Product,Flow,2017_val,2018_val,2019_val,2017_div,2018_div,2019_div,2017,2018,2019,mean
0,"Coal, peat and oil shale",Commercial and public services (PJ),0.000000,0.000000,0.000000,1.228108e+03,1.255065e+03,1.252849e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
6,"Coal, peat and oil shale",Other final consumption (PJ),3.379330,2.809778,2.581962,1.000000e+00,1.000000e+00,1.000000e+00,3.379330e+00,2.809778e+00,2.581962e+00,2.923690e+00
8,"Coal, peat and oil shale",Residential (PJ),0.000000,0.000000,0.000000,1.247773e+08,1.261908e+08,1.275755e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
12,"Crude, NGL and feedstocks",Commercial and public services (PJ),0.000000,0.000000,0.000000,1.228108e+03,1.255065e+03,1.252849e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
18,"Crude, NGL and feedstocks",Other final consumption (PJ),0.000000,0.000000,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
20,"Crude, NGL and feedstocks",Residential (PJ),0.000000,0.000000,0.000000,1.247773e+08,1.261908e+08,1.275755e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
24,Electricity,Commercial and public services (PJ),89.078403,107.795802,108.554400,1.228108e+03,1.255065e+03,1.252849e+03,7.253301e-02,8.588860e-02,8.664604e-02,8.168922e-02
31,Electricity,Other final consumption (PJ),146.005200,122.925599,116.402402,1.000000e+00,1.000000e+00,1.000000e+00,1.460052e+02,1.229256e+02,1.164024e+02,1.284444e+02
33,Electricity,Residential (PJ),469.678804,483.935800,487.792600,1.247773e+08,1.261908e+08,1.275755e+08,3.764136e-06,3.834954e-06,3.823559e-06,3.807550e-06
38,Heat,Commercial and public services (PJ),0.000000,0.000000,0.000000,1.228108e+03,1.255065e+03,1.252849e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
44,Heat,Other final consumption (PJ),0.000000,0.000000,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
46,Heat,Residential (PJ),0.000000,0.000000,0.000000,1.247773e+08,1.261908e+08,1.275755e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50,Natural gas,Commercial and public services (PJ),10.861200,11.001600,9.865801,1.228108e+03,1.255065e+03,1.252849e+03,8.843844e-03,8.765759e-03,7.874693e-03,8.494765e-03
56,Natural gas,Other final consumption (PJ),16.593302,12.281400,12.519001,1.000000e+00,1.000000e+00,1.000000e+00,1.659330e+01,1.228140e+01,1.251900e+01,1.379790e+01
58,Natural gas,Residential (PJ),29.683801,27.141299,26.946002,1.247773e+08,1.261908e+08,1.275755e+08,2.378942e-07,2.150815e-07,2.112161e-07,2.213972e-07
62,Oil products,Commercial and public services (PJ),64.878000,64.182036,61.850525,1.228108e+03,1.255065e+03,1.252849e+03,5.282758e-02,5.113840e-02,4.936790e-02,5.111130e-02
68,Oil products,Other final consumption (PJ),334.331098,316.436577,290.734038,1.000000e+00,1.000000e+00,1.000000e+00,3.343311e+02,3.164366e+02,2.907340e+02,3.138339e+02
70,Oil products,Residential (PJ),240.993502,240.993502,225.927553,1.247773e+08,1.261908e+08,1.275755e+08,1.931389e-06,1.909755e-06,1.770932e-06,1.870692e-06
75,Total,Commercial and public services (PJ),164.817602,182.979438,180.270725,1.228108e+03,1.255065e+03,1.252849e+03,1.342044e-01,1.457928e-01,1.438886e-01,1.412953e-01
82,Total,Other final consumption (PJ),500.308930,454.453359,422.237398,1.000000e+00,1.000000e+00,1.000000e+00,5.003089e+02,4.544534e+02,4.222374e+02,4.589999e+02
84,Total,Residential (PJ),740.356106,752.070601,740.666155,1.247773e+08,1.261908e+08,1.275755e+08,5.933419e-06,5.959790e-06,5.805707e-06,5.899639e-06

#### dict_rnm = {}
for k in df_pop.columns:
    col = str(k)
    if col.isnumeric():
        dict_rnm.update({k: str(int(k))})

array([[1.24777326e+08, 1.26190782e+08, 1.27575529e+08],
       [1.22810844e+12, 1.25506536e+12, 1.25284892e+12],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [54]:
df_gdp[df_gdp["Country Name"] == country]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
154,Mexico,MEX,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.413397e+11,1.484066e+11,1.553289e+11,1.679213e+11,1.879131e+11,2.012549e+11,...,1.103072e+12,1.134507e+12,1.171868e+12,1.202694e+12,1.228108e+12,1.255065e+12,1.252849e+12,1.148749e+12,NaN,NaN