In [19]:
import os, os.path

#os.chdir(r"D:\1. Projects\42. LAC Decarbonization\lac_decarbonization-servidor-05082022\lac_decarbonization-main\python")

import numpy as np
import pandas as pd
import data_structures as ds
import setup_analysis as sa
import support_functions as sf
import argparse
import warnings

from model_socioeconomic import Socioeconomic
from model_afolu import AFOLU
from model_circular_economy import CircularEconomy
from model_ippu import IPPU

In [16]:
#df_exp
df_base = pd.read_csv(os.path.join(sa.dir_ref, "fake_data", "fake_data_complete.csv"))

In [161]:
#df_base["ef_fgtv_production_fugitive_tonne_ch4_per_m3_fuel_coal"]
nations

array(['argentina', 'bahamas', 'barbados', 'belize', 'bolivia', 'brazil',
       'chile', 'colombia', 'costa_rica', 'dominican_republic', 'ecuador',
       'el_salvador', 'guatemala', 'guyana', 'haiti', 'honduras',
       'jamaica', 'mexico', 'nicaragua', 'panama', 'paraguay', 'peru',
       'suriname', 'trinidad_and_tobago', 'uruguay', 'venezuela'],
      dtype=object)

In [162]:

#load

#dir_input_data = r"D:\1. Projects\42. LAC Decarbonization\lac_decarbonization-servidor-20062022\lac_decarbonization\ref\fake_data"
#name_file = "fake_data_complete.csv"
#df_input_data =  pd.read_csv(dir_input_data+name_file)

#model_ippu = IPPU(sa.model_attributes)
#df_model_data_project = model_ippu.project(df_input_data)


#load transformations files

#load combinations of transformations to be run
dir_input_transformations = "/Users/jsyme/Downloads/Nation_level_2025"
fp_input_data = "/Users/jsyme/Downloads/data_complete_future_2022_08_24_test1-4.csv"
exp_file =  "transformations_experiment.csv"
df_exp =  pd.read_csv(os.path.join(dir_input_transformations, exp_file))


#load individual transformation files
#NOTE:the best approch is to used the calibrated parameter as a the baseline value and then have the transformation multiply that parameter

#rice management
rice_mgt =  "rice_mgt.csv"
df_rice =  pd.read_csv(os.path.join(dir_input_transformations, rice_mgt))

#Crop productivity
crop_productivity =  "Improve_Crop_Productivity.csv"
df_cproductivity =  pd.read_csv(os.path.join(dir_input_transformations, crop_productivity))

#Crop productivity with Lu gains
crop_productivityLUgains =  "Improve_Crop_Productivity_wlugains.csv"
df_cproductivityLUgains =  pd.read_csv(os.path.join(dir_input_transformations, crop_productivityLUgains))

#live stock productivity
lvst_productivity =  "Improving_Livestock_Productivity.csv"
df_lproductivity =  pd.read_csv(os.path.join(dir_input_transformations, lvst_productivity))

#live stock productivity with LUgains
lvst_productivityLUgains =  "Improving_Livestock_Productivity_wlugains.csv"
df_lproductivityLUgains =  pd.read_csv(os.path.join(dir_input_transformations, lvst_productivityLUgains))

#improving diets
new_diets =  "Improving_Diets.csv"
df_ndiets =  pd.read_csv(os.path.join(dir_input_transformations, new_diets))

#improving diets with lu gains
new_dietsLUgains =  "Improving_Diets_wlugains.csv"
df_ndietsLUgains =  pd.read_csv(os.path.join(dir_input_transformations, new_dietsLUgains))

#enteric fermentation
enteric_fermentation =  "reducing_entering_fermentation.csv"
df_efermentation =  pd.read_csv(os.path.join(dir_input_transformations, enteric_fermentation))

#conservation agriculture
conservation_agriculture =  "expand_conservation_agriculture.csv"
df_cagg =  pd.read_csv(os.path.join(dir_input_transformations, conservation_agriculture))

#reducing food losses
reducing_flosses =  "reducing_food_losses_supply_chain.csv"
df_fl=  pd.read_csv(os.path.join(dir_input_transformations, reducing_flosses))

#reducing food losses wit lu gains
reducing_flossesLUgains =  "reducing_food_losses_supply_chain_wlugains.csv"
df_flLUgains=  pd.read_csv(os.path.join(dir_input_transformations, reducing_flossesLUgains))

#managing manure
manure_management =  "managing_manure.csv"
df_mm=  pd.read_csv(os.path.join(dir_input_transformations, manure_management))

#silvopasture systems
silvopasture =  "SilvoPasture_new.csv"
df_sp=  pd.read_csv(os.path.join(dir_input_transformations, silvopasture))

#silvopasture systems with land use gains
silvopastureLUgains =  "SilvoPasture_new_wlugains.csv"
df_spLUgains=  pd.read_csv(os.path.join(dir_input_transformations, silvopastureLUgains))


#rehabilitating degraded land
rehabilitate_land =  "Rehabilitating_degraded_land.csv"
df_rhl=  pd.read_csv(os.path.join(dir_input_transformations, rehabilitate_land))

#reduce excess fertilizer
excess_fertilizer =  "reduce_excess_fertilizer.csv"
df_exf=  pd.read_csv(os.path.join(dir_input_transformations, excess_fertilizer))

#improve fertlizer app
improveapp_fertilizer =  "improve_fertilizer_app.csv"
df_impf=  pd.read_csv(os.path.join(dir_input_transformations, improveapp_fertilizer))

#reduce amounts grown
#reduce_production =  "Reducing_agg_lvst_grown.csv"
#df_rp=  pd.read_csv(os.path.join(dir_input_transformations, reduce_production)

#reduce deforestation
reduce_deforestation =  "Reducing_deforestation.csv"
df_rd=  pd.read_csv(os.path.join(dir_input_transformations, reduce_deforestation))

#none with land use gains
noneLUgains = "none_wlugains.csv"
df_nLUgains = pd.read_csv(os.path.join(dir_input_transformations, noneLUgains))


#list all policies
policies = np.unique(df_exp['Policy_ID'])
#policy_names = np.unique(df_exp['Policy_name'])
#load calibration parameters
#name_file = "data_complete_future_2022_08_03_test4.csv"
#name_file = "data_complete_future_2022_08_24_test1.csv"
#dir_calib_data = r"C:\Users\AP03054557\OneDrive\Edmundo-ITESM\3.Proyectos\42. LAC Decarbonization\Git-LAC-Calib\lac_decarbonization\calibration\AFOLU\CalibrationVectors"
df_data_calib = pd.read_csv(fp_input_data)

#dir_input_new = r"D:\1. Projects\42. LAC Decarbonization\lac_decarbonization-servidor-15072022\lac_decarbonization-main\ref\fake_data"
#name_file = "fake_data_complete.csv"
#df_input_new = pd.read_csv(dir_input_new+name_file)

#aggregate results to obtain mean values of calibration
#df_data_calib = df_data_calib.groupby(["nation"]).mean()
#df_data_calib['nation'] = df_data_calib.index

#check column names, always check if calib and policy parameters are interrelated
#df_sot.columns.isin(df_data_calib.columns)
#df_sot.columns[df_sot.columns.isin(df_data_calib.columns)==True]


#list all nations in  data calib
nations = np.unique(df_data_calib['Nation'])

#Initialize loop
df_all = []
dict_dat = {}
for policy in [0, 20]:#policies:
    dict_dat.update({policy: {}})
    
    for i in nations[0:8]:
        #policy = policies[0]
        #i= 'argentina'
        #i = 'brazil'
        #i = 'chile'
        #i = 'mexico'
        #load transformation tables
        #rice management
        trice = list(df_exp[df_exp['Policy_ID']==policy]['rice_management'])[0]
        df_trice = df_rice[(df_rice['TransformationName']==trice) & (df_rice["Nation"]==i)]

        #crop productivity
        tcproductivity = list(df_exp[df_exp['Policy_ID']==policy]['Improve_Crop_Productivity'])[0]
        df_tcproductivity = df_cproductivity[(df_cproductivity['TransformationName']==tcproductivity) & (df_cproductivity["Nation"]==i)]

        #crop productivity with LU gains
        tcproductivityLUgains = list(df_exp[df_exp['Policy_ID']==policy]['Improve_Crop_Productivity_wlugains'])[0]
        df_tcproductivityLUgains = df_cproductivityLUgains[(df_cproductivityLUgains['TransformationName']==tcproductivityLUgains) & (df_cproductivityLUgains["Nation"]==i)]

        #live stock productivity
        tlproductivity = list(df_exp[df_exp['Policy_ID']==policy]['Improve_lvst_Productivity'])[0]
        df_tlproductivity = df_lproductivity[(df_lproductivity['TransformationName']==tlproductivity) & (df_lproductivity["Nation"]==i)]

        #live stock productivity with LU gains
        tlproductivityLUgains = list(df_exp[df_exp['Policy_ID']==policy]['Improve_lvst_Productivity_wlugains'])[0]
        df_tlproductivityLUgains = df_lproductivityLUgains[(df_lproductivityLUgains['TransformationName']==tlproductivityLUgains) & (df_lproductivityLUgains["Nation"]==i)]

        #new diets
        tndiets = list(df_exp[df_exp['Policy_ID']==policy]['new_diets'])[0]
        df_tndiets = df_ndiets[(df_ndiets['TransformationName']==tndiets) & (df_ndiets["Nation"]==i)]

        #new diets with landu use gains
        tndietsLUgains = list(df_exp[df_exp['Policy_ID']==policy]['new_diets_wlugains'])[0]
        df_tndietsLUgains = df_ndietsLUgains[(df_ndietsLUgains['TransformationName']==tndietsLUgains) & (df_ndietsLUgains["Nation"]==i)]

        #enteric fermentation
        tefermentation = list(df_exp[df_exp['Policy_ID']==policy]['enteric_fermentation'])[0]
        df_tefermentation = df_efermentation[(df_efermentation['TransformationName']==tefermentation) & (df_efermentation["Nation"]==i)]

        #conservation aggriculture
        tcagg = list(df_exp[df_exp['Policy_ID']==policy]['conservation_aggriculture'])[0]
        df_tcagg = df_cagg[(df_cagg['TransformationName']==tcagg) & (df_cagg["Nation"]==i)]

        #reducing food losses
        tfl = list(df_exp[df_exp['Policy_ID']==policy]['reducing_food_losses'])[0]
        df_tfl = df_fl[(df_fl['TransformationName']==tfl) & (df_fl["Nation"]==i)]

        #reducing food losses with land use gains
        tflLUgains = list(df_exp[df_exp['Policy_ID']==policy]['reducing_food_losses_wlugains'])[0]
        df_tflLUgains = df_flLUgains[(df_flLUgains['TransformationName']==tflLUgains) & (df_flLUgains["Nation"]==i)]

        #manure management
        tmm = list(df_exp[df_exp['Policy_ID']==policy]['manure_management'])[0]
        df_tmm = df_mm[(df_mm['TransformationName']==tmm) & (df_mm["Nation"]==i)]

        #silvopasture
        tsp = list(df_exp[df_exp['Policy_ID']==policy]['silvopasture'])[0]
        df_tsp = df_sp[(df_sp['TransformationName']==tsp) & (df_sp["Nation"]==i)]

        #silvopasture with land use gains
        tspLUgains = list(df_exp[df_exp['Policy_ID']==policy]['silvopasture_wlugains'])[0]
        df_tspLUgains = df_spLUgains[(df_spLUgains['TransformationName']==tspLUgains) & (df_spLUgains["Nation"]==i)]

        #rehabilitating land
        trland = list(df_exp[df_exp['Policy_ID']==policy]['rehabilitating_land'])[0]
        df_trhl = df_rhl[(df_rhl['TransformationName']==trland) & (df_rhl["Nation"]==i)]

        #excess fertilizer
        texf = list(df_exp[df_exp['Policy_ID']==policy]['reduce_excess_fertilizer'])[0]
        df_texf = df_exf[(df_exf['TransformationName']==texf) & (df_exf["Nation"]==i)]

        #improve fertlizer app
        timpf = list(df_exp[df_exp['Policy_ID']==policy]['improve_fertilizer_app'])[0]
        df_timpf = df_impf[(df_impf['TransformationName']==timpf) & (df_impf["Nation"]==i)]

        #reduce amounts grown
        #trp = list(df_exp[df_exp['Policy_ID']==policy]['Reducing_agg_lvst_grown'])[0]
        #df_trp = df_rp[(df_rp['TransformationName']==trp) & (df_rp["Nation"]==i)]

        #reduce deforestation
        trd = list(df_exp[df_exp['Policy_ID']==policy]['deforestation'])[0]
        df_trd = df_rd[(df_rd['TransformationName']==trd) & (df_rd["Nation"]==i)]

        #none with land use gains
        tnLUgains = list(df_exp[df_exp['Policy_ID']==policy]['none_wlugains'])[0]
        df_tnLUgains = df_nLUgains[(df_nLUgains['TransformationName']==tnLUgains) & (df_nLUgains["Nation"]==i)]


        #df_input_new = df_input_data.copy(deep=True) #since data calib is now equal to fake_data_complete, no need for an additional file
        #df_input_new = df_data_calib.copy(deep=True)
        df_input_new= df_data_calib[df_data_calib['Nation']==i].copy().reset_index(drop=True)


        #modify input parameters

        #rice management
        target_Tvars = df_trice.columns[df_trice.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trice[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_trice[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #crop productivity
        target_Tvars = df_tcproductivity.columns[df_tcproductivity.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trice[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tcproductivity[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #crop productivity with lu gains
        target_Tvars = df_tcproductivityLUgains.columns[df_tcproductivityLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trice[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tcproductivityLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #livestock productivity
        target_Tvars = df_tlproductivity.columns[df_tlproductivity.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trice[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tlproductivity[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #livestock productivity with LUgains
        target_Tvars = df_tlproductivityLUgains.columns[df_tlproductivityLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trice[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tlproductivityLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #new diets
        target_Tvars = df_tndiets.columns[df_tndiets.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tndiets[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tndiets[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #new diets with land use gains
        target_Tvars = df_tndietsLUgains.columns[df_tndietsLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tndiets[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tndietsLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #enteric fermentation
        target_Tvars = df_tefermentation.columns[df_tefermentation.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tndiets[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tefermentation[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #conservation aggriculture
        target_Tvars = df_tcagg.columns[df_tcagg.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tcagg[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tcagg[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #reducing food losses
        target_Tvars = df_tfl.columns[df_tfl.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tfl[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tfl[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #reducing food losses with lu gains
        target_Tvars = df_tflLUgains.columns[df_tflLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tfl[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tflLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #manure management
        target_Tvars = df_tmm.columns[df_tmm.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tfl[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tmm[j])
        del(j)
        del(target_Tvars)

        #silvopasture
        target_Tvars = df_tsp.columns[df_tsp.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tsp[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tsp[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #silvopasture with land use gains
        target_Tvars = df_tspLUgains.columns[df_tspLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tsp[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tspLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)


        #rehabilitating land
        target_Tvars = df_trhl.columns[df_trhl.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trhl[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_trhl[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #reduce excess fertilizer
        target_Tvars = df_texf.columns[df_texf.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_texf[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_texf[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #improve fertilizer app
        target_Tvars = df_timpf.columns[df_timpf.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_timpf[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_timpf[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #reducing ammounts grown
        #target_Tvars = df_trp.columns[df_trp.columns.isin(df_input_new.columns)==True]
        #target_Tvars = target_Tvars[target_Tvars!='time_period']
        #target_Tvars = target_Tvars[target_Tvars!='Nation']
        #target_Tvars = target_Tvars[target_Tvars!='lndu_reallocation_factor']
        #for j in target_Tvars:
        #    #df_input_new[target_Tvars[0]] = np.array(df_timpf[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
        #    df_input_new[j] = np.array(df_trp[j])*np.array(df_input_new[j])
        #del(j)
        #del(target_Tvars)
        #df_input_new['lndu_reallocation_factor'] = np.array(df_trp['lndu_reallocation_factor'])

        #reduce deforestation
        target_Tvars = df_trd.columns[df_trd.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_trd[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_trd[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #none with land use gains (the process below has no effect on the run, it used only to structure consistency )
        target_Tvars = df_tnLUgains.columns[df_tnLUgains.columns.isin(df_input_new.columns)==True]
        target_Tvars = target_Tvars[target_Tvars!='time_period']
        target_Tvars = target_Tvars[target_Tvars!='Nation']
        for j in target_Tvars:
            #df_input_new[target_Tvars[0]] = np.array(df_tnLUgains[target_Tvars[0]])*np.array(df_input_new[target_Tvars[0]])
            df_input_new[j] = np.array(df_tnLUgains[j])*np.array(df_input_new[j])
        del(j)
        del(target_Tvars)

        #The lndu_rellocation factor only needs to be altered for some transformations
        if any(map(lambda x: x=="full",[tcproductivityLUgains,tlproductivityLUgains,tndietsLUgains,tflLUgains,tspLUgains,tnLUgains])):
            #new_lndu_reallocation_factor = 1.0 ; remove argentina and chile,
#            df_input_new['lndu_reallocation_factor'] = np.repeat(np.array([0.0,0.5,0.75,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]), [1,1,1,1,1,1,1,1,1,1, 26], axis=0)
             #df_input_new['lndu_reallocation_factor'] = np.repeat(np.array([0.0,0.25,0.5,0.75,1.0,1.0]), [10,1,1,1,1,22], axis=0)
              a = np.repeat(np.array([0.0]), [10], axis=0)
              b = np.linspace(start=0, stop=1.0, num=26,axis=0)
              df_input_new['lndu_reallocation_factor'] = np.concatenate([a,b])
        else :
            #new_lndu_reallocation_factor = 0.0
            df_input_new['lndu_reallocation_factor'] = 0.0

        if i=='chile' or i=='argentina':
            df_input_new['lndu_reallocation_factor'] = 0.0
        else:
            df_input_new['lndu_reallocation_factor'] = df_input_new['lndu_reallocation_factor']

        #df_input_new['lndu_reallocation_factor'] = new_lndu_reallocation_factor np.repeat(np.array([0, new_lndu_reallocation_factor]), [10, 26], axis=0)
        #df_input_new['lndu_reallocation_factor'] = np.repeat(np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0, new_lndu_reallocation_factor]), [1,1,1,1,1,1,1,1,1,1, 26], axis=0)

        #Re-scale transition probabilities
        #'pij_lndu_forests_primary
        lu_types = ['pij_lndu_croplands','pij_lndu_forests_mangroves','pij_lndu_forests_primary','pij_lndu_forests_secondary','pij_lndu_grasslands','pij_lndu_other','pij_lndu_settlements','pij_lndu_wetlands']
        for j in lu_types:
            #j = lu_types[7]
            scale_names = df_input_new.columns[pd.Series(df_input_new.columns).str.contains(j)]
            sf = df_input_new[scale_names].sum(axis=1)
            df_input_new[scale_names] = df_input_new[scale_names].div(sf, axis=0)
            #print(df_input_new[scale_names].sum(axis=1))
            del(scale_names)
            del(sf)

        #now we used df_input_new to run the model
        df_input_new = df_input_new.sort_values(by = ["time_period"]).reset_index(drop = True)
        cp = [x for x in df_base.columns if x not in df_input_new.columns]
        for x in cp:
            df_input_new[x] = np.array(df_base[x])
        
        dict_dat[policy].update({i: df_input_new})
        print("here")
        #set initial attributes of model ippu
        #model_circecon = CircularEconomy(sa.model_attributes)
        #df_output_data_waste = model_circecon.project(df_input_new)
        #df_input_data = sa.model_attributes.transfer_df_variables(df_input_new,df_output_data_waste,IPPU(sa.model_attributes).integration_variables)
        #df_input_data = pd.merge(df_input_new, df_output_data_waste, how = "left")
        """
        model_afolu = AFOLU(sa.model_attributes)
        #transfer ouput from circular economy
        #run the model
        df_output = model_afolu.project(df_input_new)
        #add ids
        df_output['Nation'] = i
        df_output['policy'] = policy
        df_output['policy_name'] = df_exp[df_exp['Policy_ID']==policy]['Policy_name'].values[0]
        df_all.append(df_output)
        del(df_output)
        del(df_input_new)
        """

#df_all = pd.concat(df_all)

here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here

In [ ]:
df_out =

In [61]:
#df_input_0 = df_input_new.copy()
#df_input_20 = df_input_new.copy()

for k in df_input_0.columns:
    if not all(df_input_0[k] == df_input_20[k]):
        print(k)

ef_fgtv_ch4_futgitive_emissions_fuel_coal
ef_fgtv_ch4_futgitive_emissions_fuel_natural_gas
ef_fgtv_ch4_futgitive_emissions_fuel_oil
ef_fgtv_ch4_futgitive_emissions_with_full_capture_fuel_oil
ef_fgtv_co2_futgitive_emissions_fuel_coal
ef_fgtv_co2_futgitive_emissions_fuel_natural_gas
ef_fgtv_co2_futgitive_emissions_fuel_oil
ef_fgtv_n2o_futgitive_emissions_fuel_coal
ef_fgtv_n2o_futgitive_emissions_fuel_natural_gas
ef_fgtv_n2o_futgitive_emissions_fuel_oil
exportsinit_fgtv_fuel_coal_tonne
exportsinit_fgtv_fuel_natural_gas_tonne
exportsinit_fgtv_fuel_oil_tonne
frac_fgtv_fugitive_capturable_ch4_captured_fuel_coal
frac_fgtv_fugitive_capturable_ch4_captured_fuel_natural_gas
frac_fgtv_fugitive_capturable_ch4_captured_fuel_oil
frac_fgtv_fugitive_ch4_flared_fuel_coal
importsinit_fgtv_fuel_coal_tonne
importsinit_fgtv_fuel_natural_gas_tonne
importsinit_fgtv_fuel_oil_tonne
initexports_enfu_pj_fuel_coal
initexports_enfu_pj_fuel_natural_gas
initexports_enfu_pj_fuel_oil
initimports_enfu_pj_fuel_coal
initimports_enfu_pj_fuel_natural_gas
initimports_enfu_pj_fuel_oil
lndu_reallocation_factor
prodinit_fgtv_fuel_coal_tonne
prodinit_fgtv_fuel_natural_gas_tonne
prodinit_fgtv_fuel_oil_tonne
ratio_fgtv_fuel_imports_to_exports_fuel_coal
ratio_fgtv_fuel_imports_to_exports_fuel_natural_gas
ratio_fgtv_fuel_imports_to_exports_fuel_oil
scalar_enfu_ratio_imports_to_exports_fuel_coal
scalar_enfu_ratio_imports_to_exports_fuel_natural_gas
scalar_enfu_ratio_imports_to_exports_fuel_oil

In [177]:
warnings.filterwarnings("ignore")
import model_afolu as ma
import importlib
importlib.reload(ma)
model_afolu_0 = ma.AFOLU(sa.model_attributes)
model_afolu_20 = ma.AFOLU(sa.model_attributes)

nation = "brazil"

df_out_0 = model_afolu_0.project(dict_dat[0][nation])
df_out_20 = model_afolu_20.project(dict_dat[20][nation])

In [174]:
#df_input_new_with_no_excess["frac_lndu_increasing_net_exports_met_grasslands"]
df_out_0[[x for x in df_out_0.columns if ("emission_co2e_subsector_" in x)]]

,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_soil
0,275.540656,-278.061279,191.285405,82.851665,790.419482,123.355401
1,275.938505,-277.889473,200.667763,94.230328,900.991580,133.703347
2,245.804646,-277.648167,209.982766,97.112758,929.658922,134.510136
3,253.093151,-277.328061,219.223249,100.119624,959.520731,137.792020
4,260.278731,-276.930105,228.382052,103.255010,990.616314,141.190555
5,267.352882,-276.455274,237.451762,106.523088,1022.985906,144.708904
6,274.313170,-275.904595,246.425420,109.855963,1054.319324,148.135220
7,281.150211,-275.536103,255.296060,113.332418,1087.050685,151.691962
8,287.862636,-275.088573,264.057158,116.956745,1121.221069,155.382806
9,294.442121,-274.563381,272.702029,120.733323,1156.872468,159.211083
10,300.887107,-273.961925,281.224449,124.666576,1194.047263,163.180576
11,307.189823,-273.285617,289.617918,128.782255,1232.043590,167.226065
12,313.348898,-272.640415,297.876706,133.067022,1271.712414,171.425833
13,319.357562,-271.916298,305.994769,137.525306,1313.094988,175.783232
14,325.215312,-271.115188,313.966226,142.161573,1356.233029,180.302045
15,330.914847,-270.238987,321.785615,146.980352,1401.168911,184.985689
16,336.456481,-269.289602,329.447885,152.088631,1448.952881,189.929766
17,341.833813,-268.172629,336.947517,157.388647,1498.621248,195.046198
18,347.047708,-266.988279,344.279612,162.885101,1550.218306,200.339083
19,352.093899,-265.738387,351.439727,168.582713,1603.788583,205.812212
20,356.969861,-264.424768,358.422886,174.486313,1659.377706,211.469589
21,361.672806,-263.049258,365.224912,180.689454,1717.781707,217.383368
22,366.202929,-261.550339,371.841665,187.108818,1778.306404,223.490517
23,370.558096,-259.993763,378.269259,193.749284,1840.997853,229.795094
24,374.737796,-258.381387,384.503831,200.615826,1905.903091,236.301349
25,378.741251,-256.715077,390.541964,207.713429,1973.069265,243.013523
26,382.567893,-254.996698,396.380220,215.138799,2043.371728,250.011161
27,386.217838,-253.155717,402.015705,222.805619,2116.037083,257.223959
28,389.690675,-251.267389,407.445525,230.718998,2191.113696,264.656283
29,392.987882,-249.333564,412.666750,238.884047,2268.649972,272.312621
30,396.115385,-247.356105,417.677146,247.305837,2348.694010,280.197703
31,399.062503,-245.336857,422.474628,256.095429,2432.293112,288.406108
32,401.837133,-243.187640,427.056785,265.152441,2518.504056,296.852526
33,404.438962,-241.001814,431.422062,274.482085,2607.376288,305.541412
34,406.872789,-238.781167,435.568784,284.089596,2698.959532,314.477571
35,409.137290,-236.527488,431.659130,293.980254,2793.303942,325.061424

In [172]:
df_out_20[[x for x in df_out_0.columns if ("emission_co2e_subsector_" in x)]]

,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_soil
0,275.540656,-278.061279,191.285405,82.851665,790.419482,123.355401
1,275.938505,-277.889473,200.667763,94.230328,900.991580,133.703347
2,245.804646,-277.648167,209.982766,97.112758,929.658922,134.510136
3,253.093151,-277.328061,219.223249,100.119624,959.520731,137.792020
4,260.278731,-276.930105,228.382052,103.255010,990.616314,141.190555
5,267.352882,-276.455274,237.451762,106.523088,1022.985906,144.708904
6,274.313170,-275.904595,246.425420,109.855963,1054.319324,148.135220
7,281.150211,-275.536103,255.296060,113.332418,1087.050685,151.691962
8,287.862636,-275.088573,264.057158,116.956745,1121.221069,155.382806
9,294.442121,-274.563381,272.702029,120.733323,1156.872468,159.211083
10,300.887107,-273.961925,122.177766,124.666576,1194.047263,163.180576
11,253.718976,-274.578127,124.427642,127.989544,1224.421611,162.934668
12,220.112144,-276.490602,128.092483,129.798453,1240.365947,161.978370
13,187.464625,-279.507810,133.125833,130.038620,1241.346978,159.481506
14,160.544422,-283.417863,139.329141,128.841249,1228.623606,155.899167
15,142.973974,-287.916026,146.388083,126.500878,1205.029428,151.778102
16,135.520628,-292.697092,153.989963,123.497619,1175.205014,147.651743
17,139.300775,-297.345610,161.783238,120.138148,1142.082797,143.923422
18,152.761143,-301.704852,169.468111,116.818623,1109.476708,140.896883
19,172.829868,-305.611967,176.829753,113.844068,1080.322370,138.681991
20,196.247633,-308.999721,183.726762,111.398676,1056.390801,137.251242
21,218.327020,-311.923747,190.191022,109.595858,1038.714571,136.395226
22,239.065481,-314.371219,196.237357,108.298307,1026.033747,135.989510
23,257.261699,-316.481545,201.918919,107.432960,1017.639353,135.879582
24,272.592563,-318.333269,207.299280,106.901782,1012.581879,135.943146
25,285.313747,-319.994250,212.398109,106.607807,1009.922267,136.097087
26,293.359245,-321.582131,217.381867,106.502771,1009.175587,136.144424
27,301.472530,-323.021696,222.227891,106.416443,1008.718602,136.234406
28,309.368343,-324.390706,226.922694,106.352901,1008.586256,136.351645
29,316.957205,-325.695870,231.451903,106.308460,1008.738840,136.485736
30,324.272787,-326.943803,235.726978,106.277091,1009.114156,136.631963
31,327.092551,-328.239646,239.938367,106.269006,1009.811297,136.514647
32,333.214206,-329.417365,243.953667,106.158017,1009.608461,136.525137
33,339.988466,-330.553991,247.724436,106.023718,1009.268896,136.570555
34,346.764211,-331.650173,251.214191,105.882233,1008.944125,136.624190
35,353.424372,-332.709124,251.568521,105.734894,1008.643238,136.679225

In [178]:
df_test = pd.read_csv("/Users/jsyme/Downloads/output_afolu_all_long.csv")

In [189]:
df_test[
    df_test["Nation"].isin(["brazil"]) &
    df_test["policy"].isin([0, 20]) & 
    df_test["variable"].isin(["emission_co2e_subsector_total_lndu"]) & 
    df_test["time_period"].isin([0, 35])
];